### ISSUE TITLE
追踪更新的返回结果都是tensor，但报了这个错误

### ISSUE THREAD

**Issue by topdou96** [jimyag/YOLOv5-DeepSort#1]
![image](https://user-images.githubusercontent.com/40995351/131961219-37a38ee0-e75e-4a0f-9e83-c0cf2bf5aeb9.png)

**Comment by jimyag** [comment]
astype is a Numpy function. Here I guess result is a tf.Tensor, so you need to use tf.cast to change its type instead (see https://www.tensorflow.org/api_docs/python/tf/cast).
